In [14]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
from pprint import pprint
import numpy as np

In [19]:
# Scrape data from website
res = requests.get("https://developers.google.com/public-data/docs/canonical/states_csv")
soup = BeautifulSoup(res.content,'lxml')
table = soup.find_all('table')[0] 
latlong_table = pd.read_html(str(table))
latlong_table = latlong_table[0]
latlong_table

   state   latitude   longitude                  name
0     AK  63.588753 -154.493062                Alaska
1     AL  32.318231  -86.902298               Alabama
2     AR  35.201050  -91.831833              Arkansas
3     AZ  34.048928 -111.093731               Arizona
4     CA  36.778261 -119.417932            California
5     CO  39.550051 -105.782067              Colorado
6     CT  41.603221  -73.087749           Connecticut
7     DC  38.905985  -77.033418  District of Columbia
8     DE  38.910832  -75.527670              Delaware
9     FL  27.664827  -81.515754               Florida
10    GA  32.157435  -82.907123               Georgia
11    HI  19.898682 -155.665857                Hawaii
12    IA  41.878003  -93.097702                  Iowa
13    ID  44.068202 -114.742041                 Idaho
14    IL  40.633125  -89.398528              Illinois
15    IN  40.551217  -85.602364               Indiana
16    KS  39.011902  -98.484246                Kansas
17    KY  37.839333  -84.270018              Kentucky
18    LA  31.244823  -92.145024             Louisiana
19    MA  42.407211  -71.382437         Massachusetts
20    MD  39.045755  -76.641271              Maryland
21    ME  45.253783  -69.445469                 Maine
22    MI  44.314844  -85.602364              Michigan
23    MN  46.729553  -94.685900             Minnesota
24    MO  37.964253  -91.831833              Missouri
25    MS  32.354668  -89.398528           Mississippi
26    MT  46.879682 -110.362566               Montana
27    NC  35.759573  -79.019300        North Carolina
28    ND  47.551493 -101.002012          North Dakota
29    NE  41.492537  -99.901813              Nebraska
30    NH  43.193852  -71.572395         New Hampshire
31    NJ  40.058324  -74.405661            New Jersey
32    NM  34.972730 -105.032363            New Mexico
33    NV  38.802610 -116.419389                Nevada
34    NY  43.299428  -74.217933              New York
35    OH  40.417287  -82.907123                  Ohio
36    OK  35.007752  -97.092877              Oklahoma
37    OR  43.804133 -120.554201                Oregon
38    PA  41.203322  -77.194525          Pennsylvania
39    PR  18.220833  -66.590149           Puerto Rico
40    RI  41.580095  -71.477429          Rhode Island
41    SC  33.836081  -81.163725        South Carolina
42    SD  43.969515  -99.901813          South Dakota
43    TN  35.517491  -86.580447             Tennessee
44    TX  31.968599  -99.901813                 Texas
45    UT  39.320980 -111.093731                  Utah
46    VA  37.431573  -78.656894              Virginia
47    VT  44.558803  -72.577841               Vermont
48    WA  47.751074 -120.740139            Washington
49    WI  43.784440  -88.787868             Wisconsin
50    WV  38.597626  -80.454903         West Virginia
51    WY  43.075968 -107.290284               Wyoming

In [17]:
# Round lat and long to 4 decimal places
latlong_table = np.round(latlong_table, decimals=4)
latlong_table

   state  latitude  longitude                  name
0     AK   63.5888  -154.4931                Alaska
1     AL   32.3182   -86.9023               Alabama
2     AR   35.2010   -91.8318              Arkansas
3     AZ   34.0489  -111.0937               Arizona
4     CA   36.7783  -119.4179            California
5     CO   39.5501  -105.7821              Colorado
6     CT   41.6032   -73.0877           Connecticut
7     DC   38.9060   -77.0334  District of Columbia
8     DE   38.9108   -75.5277              Delaware
9     FL   27.6648   -81.5158               Florida
10    GA   32.1574   -82.9071               Georgia
11    HI   19.8987  -155.6659                Hawaii
12    IA   41.8780   -93.0977                  Iowa
13    ID   44.0682  -114.7420                 Idaho
14    IL   40.6331   -89.3985              Illinois
15    IN   40.5512   -85.6024               Indiana
16    KS   39.0119   -98.4842                Kansas
17    KY   37.8393   -84.2700              Kentucky
18    LA   31.2448   -92.1450             Louisiana
19    MA   42.4072   -71.3824         Massachusetts
20    MD   39.0458   -76.6413              Maryland
21    ME   45.2538   -69.4455                 Maine
22    MI   44.3148   -85.6024              Michigan
23    MN   46.7296   -94.6859             Minnesota
24    MO   37.9643   -91.8318              Missouri
25    MS   32.3547   -89.3985           Mississippi
26    MT   46.8797  -110.3626               Montana
27    NC   35.7596   -79.0193        North Carolina
28    ND   47.5515  -101.0020          North Dakota
29    NE   41.4925   -99.9018              Nebraska
30    NH   43.1939   -71.5724         New Hampshire
31    NJ   40.0583   -74.4057            New Jersey
32    NM   34.9727  -105.0324            New Mexico
33    NV   38.8026  -116.4194                Nevada
34    NY   43.2994   -74.2179              New York
35    OH   40.4173   -82.9071                  Ohio
36    OK   35.0078   -97.0929              Oklahoma
37    OR   43.8041  -120.5542                Oregon
38    PA   41.2033   -77.1945          Pennsylvania
39    PR   18.2208   -66.5901           Puerto Rico
40    RI   41.5801   -71.4774          Rhode Island
41    SC   33.8361   -81.1637        South Carolina
42    SD   43.9695   -99.9018          South Dakota
43    TN   35.5175   -86.5804             Tennessee
44    TX   31.9686   -99.9018                 Texas
45    UT   39.3210  -111.0937                  Utah
46    VA   37.4316   -78.6569              Virginia
47    VT   44.5588   -72.5778               Vermont
48    WA   47.7511  -120.7401            Washington
49    WI   43.7844   -88.7879             Wisconsin
50    WV   38.5976   -80.4549         West Virginia
51    WY   43.0760  -107.2903               Wyoming

In [18]:
# Upload data to csv file
latlong_table.to_csv('latlong.csv')